# Dependencies
markdown:         redcarpet
redcarpet:
   extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            SGP
tagline:          'Student Growth Percentiles'
url:              http://sgp.io
shorturl:         sgp.io

author:
  name:           'Damian Betebenner'
  url:            https://twitter.com/dbetebenner

paginate:         2

github:
  repo:           https://github.com/dbetebenner/SGP

gems:
   - jekyll-redirect-from
