# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            SGP
tagline:          'Student Growth Percentiles'
description:      '.'
url:              http://sgp.io

author:
  name:           'Damian Betebenner'
  url:            https://github.com/dbetebenner

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/CenterForAssessment/SGP
